#! /usr/bin/env python3
# coding: utf-8


def parse(data):

    stopwords = ["a", "abord", "absolument", "afin", "ah", "ai", "aie", "ailleurs", "ainsi", "ait", "allaient",
                 "allo",
                 "allons", "allô", "alors", "anterieur", "anterieure", "anterieures", "apres", "après", "as",
                 "assez",
                 "attendu", "au", "aucun", "aucune", "aujourd", "aujourd'hui", "aupres", "auquel", "aura",
                 "auraient",
                 "aurait", "auront", "aussi", "autre", "autrefois", "autrement", "autres", "autrui", "aux",
                 "auxquelles",
                 "auxquels", "avaient", "avais", "avait", "avant", "avec", "avoir", "avons", "ayant", "b",
                 "bah", "bas",
                 "basee", "bat", "beau", "beaucoup", "bien", "bigre", "boum", "bravo", "brrr", "c", "car",
                 "ce", "ceci",
                 "cela", "celle", "celle-ci", "celle-là", "celles", "celles-ci", "celles-là", "celui",
                 "celui-ci",
                 "celui-là", "cent", "cependant", "certain", "certaine", "certaines", "certains", "certes",
                 "ces", "cet",
                 "cette", "ceux", "ceux-ci", "ceux-là", "chacun", "chacune", "chaque", "cher", "chers", "chez",
                 "chiche",
                 "chut", "chère", "chères", "ci", "cinq", "cinquantaine", "cinquante", "cinquantième",
                 "cinquième", "clac",
                 "clic", "combien", "comme", "comment", "comparable", "comparables", "compris", "concernant",
                 "contre",
                 "couic", "crac", "d", "da", "dans", "de", "debout", "dedans", "dehors", "deja", "delà",
                 "depuis",
                 "dernier", "derniere", "derriere", "derrière", "des", "desormais", "desquelles", "desquels",
                 "dessous",
                 "dessus", "deux", "deuxième", "deuxièmement", "devant", "devers", "devra", "different",
                 "differentes",
                 "differents", "différent", "différente", "différentes", "différents", "dire", "directe",
                 "directement",
                 "dit", "dite", "dits", "divers", "diverse", "diverses", "dix", "dix-huit", "dix-neuf",
                 "dix-sept",
                 "dixième", "doit", "doivent", "donc", "dont", "douze", "douzième", "dring", "du", "duquel",
                 "durant",
                 "dès", "désormais", "e", "effet", "egale", "egalement", "egales", "eh", "elle", "elle-même",
                 "elles",
                 "elles-mêmes", "en", "encore", "enfin", "entre", "envers", "environ", "es", "est", "et",
                 "etant", "etc",
                 "etre", "eu", "euh", "eux", "eux-mêmes", "exactement", "excepté", "extenso", "exterieur", "f",
                 "fais",
                 "faisaient", "faisant", "fait", "façon", "feront", "fi", "flac", "floc", "font", "g", "gens",
                 "h", "ha",
                 "hein", "hem", "hep", "hi", "ho", "holà", "hop", "hormis", "hors", "hou", "houp", "hue",
                 "hui", "huit",
                 "huitième", "hum", "hurrah", "hé", "hélas", "i", "il", "ils", "importe", "j", "je", "jusqu",
                 "jusque",
                 "juste", "k", "l", "la", "laisser", "laquelle", "las", "le", "lequel", "les", "lesquelles",
                 "lesquels",
                 "leur", "leurs", "longtemps", "lors", "lorsque", "lui", "lui-meme", "lui-même", "là", "lès",
                 "m", "ma",
                 "maint", "maintenant", "mais", "malgre", "malgré", "maximale", "me", "meme", "memes", "merci",
                 "mes",
                 "mien", "mienne", "miennes", "miens", "mille", "mince", "minimale", "moi", "moi-meme",
                 "moi-même",
                 "moindres", "moins", "mon", "moyennant", "multiple", "multiples", "même", "mêmes", "n", "na",
                 "naturel",
                 "naturelle", "naturelles", "ne", "neanmoins", "necessaire", "necessairement", "neuf",
                 "neuvième", "ni",
                 "nombreuses", "nombreux", "non", "nos", "notamment", "notre", "nous", "nous-mêmes", "nouveau",
                 "nul",
                 "néanmoins", "nôtre", "nôtres", "o", "oh", "ohé", "ollé", "olé", "on", "ont", "onze",
                 "onzième", "ore",
                 "ou", "ouf", "ouias", "oust", "ouste", "outre", "ouvert", "ouverte", "ouverts", "o|", "où",
                 "p", "paf",
                 "pan", "par", "parce", "parfois", "parle", "parlent", "parler", "parmi", "parseme", "partant",
                 "particulier", "particulière", "particulièrement", "pas", "passé", "pendant", "pense",
                 "permet",
                 "personne", "peu", "peut", "peuvent", "peux", "pff", "pfft", "pfut", "pif", "pire", "plein",
                 "plouf",
                 "plus", "plusieurs", "plutôt", "possessif", "possessifs", "possible", "possibles", "pouah",
                 "pour",
                 "pourquoi", "pourrais", "pourrait", "pouvait", "prealable", "precisement", "premier",
                 "première",
                 "premièrement", "pres", "probable", "probante", "procedant", "proche", "près", "psitt", "pu",
                 "puis",
                 "puisque", "pur", "pure", "q", "qu", "quand", "quant", "quant-à-soi", "quanta", "quarante",
                 "quatorze",
                 "quatre", "quatre-vingt", "quatrième", "quatrièmement", "que", "quel", "quelconque", "quelle",
                 "quelles",
                 "quelqu'un", "quelque", "quelques", "quels", "qui", "quiconque", "quinze", "quoi", "quoique",
                 "r", "rare",
                 "rarement", "rares", "relative", "relativement", "remarquable", "rend", "rendre", "restant",
                 "reste",
                 "restent", "restrictif", "retour", "revoici", "revoilà", "rien", "s", "sa", "sacrebleu",
                 "sait", "sans",
                 "sapristi", "sauf", "se", "sein", "seize", "selon", "semblable", "semblaient", "semble",
                 "semblent",
                 "sent", "sept", "septième", "sera", "seraient", "serait", "seront", "ses", "seul", "seule",
                 "seulement",
                 "si", "sien", "sienne", "siennes", "siens", "sinon", "six", "sixième", "soi", "soi-même",
                 "soit",
                 "soixante", "son", "sont", "sous", "souvent", "specifique", "specifiques", "speculatif",
                 "stop",
                 "strictement", "subtiles", "suffisant", "suffisante", "suffit", "suis", "suit", "suivant",
                 "suivante",
                 "suivantes", "suivants", "suivre", "superpose", "sur", "surtout", "t", "ta", "tac", "tant",
                 "tardive",
                 "te", "tel", "telle", "tellement", "telles", "tels", "tenant", "tend", "tenir", "tente",
                 "tes", "tic",
                 "tien", "tienne", "tiennes", "tiens", "toc", "toi", "toi-même", "ton", "touchant", "toujours",
                 "tous",
                 "tout", "toute", "toutefois", "toutes", "treize", "trente", "tres", "trois", "troisième",
                 "troisièmement",
                 "trop", "très", "tsoin", "tsouin", "tu", "té", "u", "un", "une", "unes", "uniformement",
                 "unique",
                 "uniques", "uns", "v", "va", "vais", "vas", "vers", "via", "vif", "vifs", "vingt", "vivat",
                 "vive",
                 "vives", "vlan", "voici", "voilà", "vont", "vos", "votre", "vous", "vous-mêmes", "vu", "vé",
                 "vôtre",
                 "vôtres", "w", "x", "y", "z", "zut", "à", "â", "ça", "ès", "étaient", "étais", "était",
                 "étant", "été",
                 "être", "ô"]
    extras = [".", "?", ":", ";", "/", "!", "-", "je", "tu", "il", "nous",
              "vous", "ils", "elle", "elles", "l'adresse", "qu'elle"]
    verbs = ["dormir", "rapprocher", "chérir", "faxer", "deviner", "attenter", "applaudir", "durcir",
             "écouter", "aboutir", "diverger", "désespérer", "rémunérer", "ciseler", "rôder", "assainir",
             "bosser", "initier",
             "forger", "vendre", "fendre", "mordre", "chanceler", "habituer", "décrier", "défoncer", "charger",
             "débattre",
             "appréhender", "cumuler", "dégénérer", "adhérer", "haver", "émaner", "interdire", "survivre",
             "accaparer",
             "activer", "monnayer", "coincer", "coïncider", "chanter", "épuiser", "stupéfaire", "occlure",
             "interpeller",
             "provoquer", "grêler", "resserrer", "figer", "têter", "posséder", "rentrer", "ronronner",
             "brosser",
             "surveiller", "décroître", "influencer", "haïr", "importer", "visser", "conjuguer", "caver",
             "vivre",
             "obscurcir", "découvrir", "doubler", "balader", "rester", "penser", "barrir", "recevoir",
             "multiplier",
             "valoir", "conditionner", "muter", "charrier", "tacher", "délivrer", "souligner", "durer",
             "réagir",
             "celer", "revouloir", "daigner", "ronfler", "stipuler", "constituer", "réciter", "entreprendre",
             "épousseter", "expédier", "nouer", "damner", "redevenir", "envahir", "comparer", "escalader",
             "heurter",
             "moudre", "débarrasser", "perdre", "attiser", "émuler", "dénoncer", "positionner", "sourire",
             "rembourser",
             "bourrer", "récolter", "embraser", "alléguer", "fléchir", "former", "cliquer", "venir",
             "intriguer", "caner",
             "stupéfier", "verser", "piquer", "caractériser", "dépanner", "étoffer", "incliner", "nager",
             "boîter", "axer",
             "fasciner", "exclamer", "quitter", "inviter", "briller", "acharner", "attester", "redescendre",
             "dorloter", "méditer", "négliger", "exposer", "avoyer", "louer", "réfugier", "appeler", "trotter",
             "couiner",
             "intégrer", "épandre", "larguer", "abriter", "confier", "doler", "inhiber", "vaquer", "admettre",
             "envelopper", "suggérer", "carreler", "négocier", "conclure", "boiter", "refermer", "couver",
             "importuner", "diminuer",
             "déchiqueter", "dégourdir", "laper", "poindre", "emboire", "rassir", "abêtir", "bienvenir",
             "crotter", "vagir",
             "reproduire", "chuter", "geindre", "pousser", "stopper", "marteler", "réviser", "obtempérer",
             "embatre", "téter", "presser", "gréver", "détendre", "allier", "aligner", "décoller", "tourner",
             "vénérer",
             "rabattre", "entourer", "bâiller", "éclore", "hausser", "brancher", "dessiner", "étendre",
             "abîmer", "souder", "migrer", "franchir", "digérer", "frayer", "irriter", "apparaître",
             "regrouper",
             "broyer", "ressortir", "déployer", "disjoindre", "sevrer", "zézayer", "revivre", "déballer",
             "mouiller",
             "vaguer", "asseoir", "créditer", "toiler", "débarquer", "résister", "répandre", "engloutir",
             "dévoyer",
             "bramer", "rasseoir", "célébrer", "transporter", "arrêter", "arrondir", "enquérir", "empiéter",
             "dédier",
             "diriger", "luire", "bailler", "suer", "tendre", "réunir", "doper", "aiguiser", "lancer",
             "confronter",
             "payer", "efforcer", "muer", "poiler", "arguer", "asséner", "découper", "sauver", "dégager",
             "éprouver",
             "amasser", "fouetter", "retarder", "apposer", "retomber", "interviewer", "paner", "pâtir",
             "projeter",
             "délayer", "acquérir", "emporter", "formater", "vernir", "téléphoner", "contrer", "accroire",
             "perturber",
             "soûler", "déblatérer", "récompenser", "réconforter", "arranger", "couvrir", "habiller",
             "contredire",
             "entrer", "affiner", "pendre", "assener", "reculer", "poster", "dominer", "circonscrire",
             "bonifier",
             "tremper", "ébattre", "obéir", "titiller", "effacer", "prêcher", "capeler", "demander",
             "convoiter",
             "basculer", "faciliter", "brimbaler", "doucher", "rassasier", "adjoindre", "viner", "accroître",
             "bruire",
             "happer", "inonder", "contrefaire", "astreindre", "maugréer", "pouvoir", "apitoyer", "renvoyer",
             "connecter", "intervertir", "opter", "prendre", "amerrir", "accommoder", "atteler", "jouer",
             "réaliser",
             "abasourdir", "effectuer", "suicider", "peser", "gravir", "taper", "peigner", "punir",
             "reprendre", "fauter",
             "enfouir", "dire", "fâcher", "caser", "comprendre", "figurer", "crier", "recréer", "renouveler",
             "ressembler", "trembler", "écoeurer", "altérer", "léguer", "quémander", "renier", "curer",
             "saler", "plonger", "immiscer",
             "enrhumer", "rassurer", "sceller", "mouler", "répéter", "hurler", "mouver", "hériter", "remonter",
             "manifester", "complaire", "évoluer", "correspondre", "disperser", "tarder", "imiter",
             "planifier", "regarder",
             "fader", "exciter", "bonder", "supposer", "adonner", "transformer", "trahir", "revaloir",
             "repérer",
             "espérer", "glacer", "décevoir", "brayer", "acter", "démordre", "commencer", "finaliser",
             "modifier",
             "quérir", "douter", "skier", "sursauter", "entacher", "ennoyer", "occire", "expirer", "panser",
             "parvenir", "aérer",
             "devoir", "énouer", "conserver", "investiguer", "miauler", "éclabousser", "oindre", "réfléchir",
             "persuader", "concéder",
             "arriver", "héberger", "affecter", "agenouiller", "anticiper", "côcher", "apparier", "bâter",
             "changer", "miner", "priser", "entendre", "acheter", "huer", "référencer", "allumer", "râler",
             "oeuvrer",
             "ensevelir", "interroger", "dégoûter", "encourager", "perdurer", "supputer", "renverser",
             "raffoler",
             "confectionner", "layer", "redémarrer", "retirer", "vérifier", "danser", "agripper", "exiger",
             "destiner",
             "pardonner", "unir", "pleuvoir", "cacher", "hâler", "plaire", "chercher", "conquérir", "ranger",
             "jaser", "soucier", "arracher", "viser", "agrafer", "élaguer", "teinter", "épater", "détenir",
             "éclaircir",
             "enfler", "partager", "rouler", "dévorer", "nominer", "puer", "reposer", "passionner",
             "répertorier",
             "remuer", "grossir", "persévérer", "fraîchir", "discuter", "effrayer", "approprier", "cultiver",
             "agréer",
             "ravir", "assortir", "feindre", "convoquer", "méfier", "attarder", "tendre", "rassembler",
             "soutenir",
             "paître", "haïr",
             "souhaiter", "taire", "bavarder", "enchérir", "flotter", "tiédir", "narrer", "ressentir",
             "bouler", "désapprendre", "grogner", "jaillir", "détailler", "défendre", "souffrir", "repleuvoir",
             "accoucher", "baver", "sélectionner", "dénigrer", "sauter", "languir", "restreindre", "cesser",
             "mêler",
             "progresser", "animer", "débuter", "dispenser", "stresser", "sacrifier", "réapparaître", "bleuir",
             "étudier",
             "avoir", "adresser", "risquer", "décharger", "autoriser", "jalouser", "aborder", "choper",
             "remplacer",
             "allécher", "consister", "concourir", "réer", "tripoter", "rapatrier", "relater", "héler",
             "repeindre",
             "précéder", "sentir", "influer", "garer", "prévenir", "compatir", "peinturer", "patiner",
             "profiter",
             "primer", "épier",
             "grandir", "libérer", "ployer", "abandonner", "corréler", "sommer", "ravager", "contrôler",
             "attendre", "embarquer", "séduire", "aménager", "approvisionner", "jeûner", "débouillir",
             "protéger", "fêler",
             "roser", "blâmer", "appuyer", "pager", "alunir", "contribuer", "daller", "déconner", "inclure",
             "attacher",
             "coûter", "endurer", "affronter", "conseiller", "refuser", "seoir", "alourdir", "exécrer",
             "distraire",
             "substituer",
             "rebondir", "travailler", "doter", "noter", "craindre", "déchirer", "murmurer", "choisir",
             "assurer",
             "administrer", "foudroyer", "imaginer", "découdre", "préconiser", "rechercher", "réparer",
             "situer",
             "modeler",
             "intervenir", "orner", "enlacer", "tricher", "éloigner", "failler", "revendre", "convier",
             "excuser",
             "abreuver", "privilégier", "discourir", "donner", "tutoyer", "mener", "désirer", "agir",
             "supprimer",
             "revendiquer", "paraître", "promener", "côtoyer", "croître", "prédire", "rayer", "rallier",
             "courir",
             "briser",
             "luter", "fier", "houer", "plaider", "budgéter", "exceller", "humilier", "galoper", "fiancer",
             "congeler",
             "placer", "lacer", "aluner", "parcourir", "récréer", "appartenir", "débloquer", "rire", "abonder",
             "embellir", "choquer", "clore", "équivaloir", "réchauffer", "aspirer", "retourner", "couper",
             "interrompre",
             "fouir", "pourvoir", "rougir", "rajeunir", "recoudre", "déposer", "réitérer", "démentir",
             "barrer",
             "agrandir",
             "scinder", "déblayer", "munir", "redire", "exempter", "savonner", "impatienter", "gazer",
             "énoncer",
             "scruter",
             "finir", "tomber", "rêver", "mimer", "favoriser", "gourer", "abstraire", "avancer", "visionner",
             "mentir",
             "épargner", "réinscrire", "émouvoir", "défiler", "assujettir", "démener", "frémir", "foncer",
             "questionner",
             "raser", "piper", "mollir", "dépêcher", "pauser", "allonger", "entrevoir", "écraser", "procurer",
             "étourdir",
             "assassiner", "préserver", "mettre", "dérouler", "proposer", "abrutir", "télécharger", "médire",
             "férir",
             "suppléer", "peiner", "tolérer", "mécroire", "visiter", "jurer", "embrayer", "hanter", "plaindre",
             "délier",
             "fréquenter", "ennuyer", "amenuiser", "réveiller", "offenser", "enclore", "airer", "polluer",
             "replier",
             "accabler", "participer", "lotir", "embaucher", "implémenter", "atténuer", "bouleverser",
             "préciser",
             "incomber", "baisser", "pétrir", "défrayer", "chauffer", "lever", "moucher", "consulter",
             "licencier",
             "percevoir", "lutter", "advenir", "attirer", "ajouter", "évanouir", "pondre", "éplucher",
             "grever",
             "accuser",
             "diviser", "manager", "mijoter", "parfaire", "restaurer", "remplir", "abonner", "affaiblir",
             "enjoindre",
             "secouer", "voyager", "démolir", "emplir", "surfaire", "notifier", "récrire", "critiquer",
             "effondrer",
             "corriger", "détruire", "interférer", "servir", "voiler", "alléger", "empresser", "buriner",
             "enchanter",
             "brouter", "assombrir", "différencier", "assouplir", "nier", "mûrir", "continuer", "luxer",
             "chaloir",
             "mater",
             "absenter", "programmer", "acquitter", "calculer", "classer", "encourir", "tapir", "attraper",
             "aciseler",
             "émier", "assumer", "gratter", "exercer", "déplacer", "cramer", "défaillir", "repaître",
             "endormir",
             "insister", "dîner", "naviguer", "gémir", "vêler", "représenter", "disconvenir", "rater",
             "résider",
             "enfoncer", "débiter", "breveter", "assommer", "cogner", "égarer", "évaluer", "seller", "équiper",
             "accumuler",
             "configurer", "résulter", "vanter", "traire", "embêter", "agréger", "prescrire", "battre",
             "bouillir",
             "recommencer", "rêvasser", "promouvoir", "saisir", "tatouer", "sommeiller", "compléter", "ruer",
             "fureter",
             "lire", "uriner", "intéresser", "fusionner", "interagir", "offrir", "entamer", "soupirer",
             "assister",
             "rattacher", "entre", "tressaillir", "disparaître", "revêtir", "suivre", "déceler", "rétablir",
             "voter",
             "aimer", "tenir", "hennir", "élargir", "envier", "céder", "mander", "soulever", "gaspiller",
             "pérenniser",
             "gager", "apprécier", "bâtir", "flûter", "départir", "échoir", "tanner", "poursuivre", "soulager",
             "venger",
             "muser", "décourager", "énumérer", "conférer", "cirer", "enorgueillir", "festoyer", "duper",
             "prêter",
             "ouvrir", "emballer", "pratiquer", "souscrire", "diagnostiquer", "joindre", "surfer", "moquer",
             "tramer",
             "relire", "recéler", "pencher", "compromettre", "démunir", "voleter", "grignoter",
             "transparaître",
             "étreindre", "avaler", "divorcer", "nécessiter", "susciter", "chahuter", "lasser", "régaler",
             "tasser",
             "survenir", "garantir", "enflammer", "imposer", "dévier", "panner", "tournoyer", "renoncer",
             "soustraire",
             "caler", "entériner", "avouer", "décommettre", "partir", "référer", "crever", "désister", "léser",
             "commettre",
             "pédaler", "souper", "apprêter", "compter", "bayer", "étiqueter", "regretter", "guider",
             "identifier",
             "raisonner", "approcher", "fouiller", "siéger", "recenser", "trouver", "roder", "blesser",
             "convenir",
             "éprendre", "saluer", "balayer", "expliquer", "décorer", "blêmir", "vaincre", "sonner",
             "développer",
             "régir",
             "exagérer", "méprendre", "maintenir", "capter", "savoir", "vanner", "oser", "bricoler", "songer",
             "abstenir",
             "voguer", "cocher", "réjouir", "opposer", "octroyer", "conjurer", "ronger", "essouffler",
             "toucher",
             "transmettre", "émoudre", "entretenir", "détester", "blottir", "accroupir", "dupliquer",
             "déclarer",
             "employer", "peindre", "maigrir", "impliquer", "absoudre", "déclencher", "cracher", "élancer",
             "adoucir",
             "déménager", "enduire", "pallier", "cherrer", "maudire", "dédicacer", "assagir", "sustenter",
             "augmenter",
             "moisir", "échapper", "clarifier", "extasier", "foirer", "proscrire", "accourir", "glander",
             "constater",
             "baigner", "coter", "succomber", "amuser", "abaisser", "siffler", "solliciter", "fabriquer",
             "réduire", "égaler", "enivrer", "produire", "terminer", "refaire", "signaler", "soudoyer",
             "querir",
             "évoquer",
             "encaisser", "écouler", "agonir", "dépendre", "convoyer", "décider", "égrener", "facturer",
             "aliéner",
             "gueuler", "rédiger", "biser", "prodiguer", "chialer", "plaisanter", "justifier", "détaler",
             "croire",
             "menacer", "qualifier", "dégeler", "prévaloir", "tracasser", "fonder", "nourrir", "clignoter",
             "enfreindre", "relier", "spécifier", "prolonger", "dialoguer", "gésir", "métrer", "noircir",
             "juger",
             "souffler", "damer", "colorier", "bondir", "parier", "salir", "braire", "émerger", "causer",
             "confondre",
             "énucléer", "éteindre", "cacheter", "varier", "fleurir", "éjaculer", "gronder", "saigner",
             "freiner",
             "redonner", "rigoler", "insérer", "éviter", "atterrir", "casser", "échanger", "rattraper",
             "diffuser",
             "aiguiller", "décéder", "toquer", "raconter", "améliorer", "vomir", "fêter", "bander", "lier",
             "apaiser",
             "combattre", "retransmettre", "introduire", "fermer", "relever", "amoindrir", "verdir",
             "circoncire",
             "entendre", "observer", "remporter", "corroborer", "trier", "concilier", "occuper", "laver",
             "enthousiasmer",
             "étinceler", "mourir", "ceindre", "fixer", "embrasser", "pulluler", "résilier", "affectionner",
             "reconquérir",
             "dater", "éclater", "motiver", "clouer", "leurrer", "ouïr", "combiner", "virer", "éternuer",
             "tinter",
             "aller",
             "envisager", "adopter", "voûter", "noyer", "entrouvrir", "remercier", "consommer", "collaborer",
             "insinuer",
             "enquêter", "arroser", "châtier", "divulguer", "adorer", "recontacter", "enchaîner", "officier",
             "aider",
             "disputer", "croquer", "toiser", "doigter", "apparoir", "complexifier", "troubler", "boire",
             "amuïr",
             "isoler",
             "glisser", "mélanger", "gréer", "ravoir", "guérir", "vieillir", "baser", "ocrer", "quêter",
             "rectifier",
             "reparler", "filer", "illuminer", "démissionner", "requérir", "blaguer", "bouger", "atterrer",
             "refroidir",
             "tonner", "ordonner", "dépérir", "imprimer", "honnir", "descendre", "fournir", "exclure",
             "farcir",
             "démanteler", "subsister", "ficeler", "contrarier", "attribuer", "féliciter", "obliger",
             "falloir",
             "fourvoyer", "exister", "narguer", "enrichir", "assiéger", "prouver", "paramétrer", "différer",
             "garnir",
             "brûler", "éberluer", "supplier", "ébahir", "mirer", "inaugurer", "gagner", "éveiller",
             "accrocher",
             "frôler", "renommer", "forer", "bousculer", "collecter", "fuir", "refléter", "résumer",
             "pressentir",
             "abuser",
             "déraper", "mouvoir", "faner", "ramasser", "frire", "éconduire", "grasseyer", "tirer", "dicter",
             "approfondir",
             "halluciner", "épeler", "laisser", "sourdre", "préétablir", "colorer", "attaquer", "contraindre",
             "aciérer",
             "repentir", "surseoir", "recueillir", "déroger", "brandir", "garder", "compenser", "peaufiner",
             "annoncer",
             "détériorer", "chuchoter", "coller", "aggraver", "modérer", "osciller", "ressaisir", "suffire",
             "habiter",
             "conduire", "assimiler", "priver", "engueuler", "solutionner", "dépasser", "recouvrer", "envoler",
             "nommer",
             "acheminer", "relâcher", "masser", "sous","stocker", "illustrer", "brunir", "vouvoyer",
             "coudre",
             "ouvrer",
             "charmer", "déguster", "urger", "savourer", "déglutir", "harceler", "marrer", "assembler",
             "sauvegarder",
             "bénir", "contempler", "apprendre", "ternir", "éditer", "violer", "composer", "brumer", "railler",
             "recouvrir",
             "courre", "patienter", "receler", "bronzer", "engendrer", "aviser", "douer", "excéder",
             "secourir",
             "meurtrir",
             "manipuler", "chasser", "simplifier", "boucher", "desservir", "relancer", "avertir", "contenter",
             "pâlir",
             "façonner", "commenter", "dévoiler", "éblouir", "impartir", "reporter", "pourrir", "vexer",
             "désobéir",
             "planer", "assaillir", "démarrer", "zapper", "guetter", "préférer", "murer", "devancer", "nuer",
             "entraîner", "abolir", "postuler", "avérer", "confire", "draguer", "couler", "polir", "rager",
             "photographier",
             "étrécir", "déléguer", "compliquer", "traduire", "réécrire", "élire", "obséder", "hésiter",
             "régner",
             "emmener", "pêcher", "reluire", "désigner", "allouer", "ensuivre", "neiger", "provenir",
             "aguerrir",
             "foutre",
             "assouvir", "ramener", "fumer", "réessayer", "puiser", "calmer", "abattre", "reconnaître",
             "étonner",
             "emmêler", "tarer", "répartir", "naître", "veiller", "comparaître", "dépenser", "béer", "parer",
             "paver",
             "baptiser", "saouler", "endommager", "dépecer", "épiner", "explorer", "marier", "recourir",
             "débrouiller",
             "haleter", "croupir", "repasser", "préoccuper", "clôturer", "distinguer", "éliminer", "rincer",
             "raidir",
             "accoler", "suspendre", "omettre", "déguerpir", "intensifier", "enfuir", "inverser", "vouloir",
             "hacher",
             "sévir", "estimer", "gâter", "recopier", "renaître", "vaser", "aplanir", "rencontrer", "renter",
             "ralentir",
             "concerner", "persister", "caracoler", "percer", "indiquer", "accomplir", "étouffer", "accepter",
             "aliter",
             "traîner", "précipiter", "japper", "devenir", "saurer", "issir", "séjourner", "caqueter",
             "cotiser",
             "amonceler", "essayer", "essuyer", "dénuer", "ressayer", "bouter", "pénétrer", "empirer",
             "contrevenir",
             "aventurer", "actualiser", "marquer", "embarrasser", "déranger", "rapetisser", "taler", "publier",
             "poser",
             "tuiler", "rafraîchir", "étrenner", "flamboyer", "inciter", "réélire", "occasionner", "relayer",
             "porter",
             "retrouver", "apporter", "associer", "appauvrir", "branler", "prétendre", "dissiper", "exaucer",
             "agiter",
             "filmer", "impacter", "creuser", "imprégner", "accueillir", "lamenter", "conformer", "peler",
             "dévêtir",
             "trouer", "additionner", "prévoir", "repartir", "effleurer", "dissoudre", "pointer", "balancer",
             "revoir",
             "pleurer", "recruter", "envoyer", "mendier", "passer", "émettre", "dresser", "craquer",
             "accélérer",
             "prononcer", "apercevoir", "flâner", "définir", "soumettre", "imager", "subvenir", "dévouer",
             "orienter",
             "raccourcir", "meuler", "raccrocher", "remémorer", "affirmer", "préparer", "épouser", "remettre",
             "copier",
             "enter", "adapter", "frapper", "déchoir", "courbaturer", "affliger", "rôtir", "condamner",
             "décrire",
             "dépeindre", "décrocher", "vouer", "empêcher", "frotter", "égayer", "prôner", "haler", "citer",
             "nuire",
             "rompre", "réserver", "défaire", "serrer", "goûter", "lécher", "draper", "communiquer",
             "npagayer",
             "investir", "disposer", "havir", "déduire", "enregistrer", "taquiner", "pelleter", "chevaucher",
             "caper",
             "tomer", "réglementer", "enseigner", "interpréter", "oublier", "étaler", "tousser", "sécher",
             "cloner",
             "ester", "messeoir", "jeter", "impressionner", "sucer", "manier", "régler", "poter",
             "siroter",
             "kiffer", "alimenter", "repousser", "mincir", "montrer", "collectionner", "habiliter",
             "attendrir", "établir", "surgir", "apeurer", "adire", "agresser", "énerver", "monter", "annoter",
             "accéder",
             "parler", "connaître", "restituer", "certifier", "obtenir", "venter", "besogner", "apparenter",
             "rouvrir",
             "redécouvrir", "écrire", "aplatir", "circuler", "lister", "confirmer", "enlever", "claquer",
             "retentir",
             "exprimer", "échouer", "botter", "commercer", "bouffer", "manger", "inquiéter", "annihiler",
             "tailler",
             "diluer", "séparer", "parrainer", "anéantir", "enfiler", "inscrire", "user", "chausser",
             "marcher",
             "racheter",
             "instruire", "égrainer", "ficher", "ressusciter", "réclamer", "désoler", "procéder", "affermir",
             "signer",
             "rajouter", "écrier", "démettre", "construire", "induire", "rayonner", "déteindre", "demeurer",
             "déjeuner",
             "jongler", "statuer", "suffoquer", "créer", "saillir", "valider", "amener", "graver", "retenir",
             "bêler",
             "coordonner", "redevoir", "agacer", "coiffer", "comporter", "rejeter", "scanner", "pincer",
             "concurrencer",
             "tarir", "réussir", "défier", "élaborer", "mentionner", "remédier", "lamer", "déborder", "livrer",
             "cueillir",
             "alerter", "aboyer", "permettre", "saloper", "concevoir", "louvoyer", "périr", "lover", "subir",
             "amourer",
             "cuisiner", "feuilleter", "bégayer", "ménager", "fonctionner", "dorer", "rappeler", "mériter",
             "fondre",
             "soupçonner", "prénommer", "promettre", "renforcer", "convertir", "exploiter", "transférer",
             "lainer",
             "humer",
             "fatiguer", "miser", "remarquer", "croiser", "distribuer", "planter", "gonfler", "resservir",
             "élever",
             "traverser", "renseigner", "abhorrer", "enterrer", "emparer", "gîter", "recommander", "respirer",
             "formuler",
             "saper", "évader", "épanouir", "contacter", "surprendre", "semer", "koter", "rendre", "inspirer",
             "supporter",
             "ramer", "accentuer", "afficher", "divertir", "reconduire", "niveler", "réapprendre", "amplifier",
             "revenir",
             "mesurer", "déplier", "bouder", "tondre", "dédire", "roquer", "emprunter", "habler", "sertir",
             "générer",
             "longer", "être", "jaunir", "tâter", "confesser", "témoigner", "crosser", "piéger",
             "réceptionner",
             "démontrer", "boiser", "corrompre", "concentrer", "maîtriser", "teindre", "exécuter", "achever",
             "affranchir",
             "extraire", "flatter", "asservir", "transcrire", "loger", "conjoindre", "gâcher", "affoler",
             "écher",
             "jouir", "voler", "mâcher", "accorder", "huir", "lâcher", "éclairer", "sembler", "révéler",
             "déboucher",
             "assoupir", "tricoter", "appendre", "signifier", "emménager", "consumer", "biner", "approuver",
             "exploser",
             "balbutier", "éduquer", "convaincre", "nettoyer", "grimper", "évacuer", "prier", "réconcilier",
             "atteindre",
             "familiariser", "tâcher", "tester", "juter", "autosuggestionner", "forcer", "détacher", "pifer",
             "rimer",
             "dénier", "ignorer", "utiliser", "détecter", "tenter", "succéder", "déprimer", "manquer", "rugir",
             "reprocher",
             "souvenir", "coucher", "mâter", "caresser", "geler", "déterminer", "renchérir", "répondre",
             "susurrer",
             "ruisseler", "raire", "accompagner", "vider", "consacrer", "arborer", "gérer", "limiter",
             "bloquer",
             "voir",
             "installer", "vêtir", "décliner", "fuser", "traiter", "bercer", "tromper", "empreindre",
             "rapporter",
             "ioder",
             "froisser", "rouspéter", "rejoindre", "hâter", "contenir", "analyser", "verrouiller", "blanchir",
             "subodorer",
             "examiner", "ourdir", "dessaisir", "consentir", "choyer", "présenter", "appliquer", "bénéficier",
             "amorcer",
             "résonner", "déshabiller", "plier", "cogiter", "faire", "retranscrire", "maquiller", "rétrécir",
             "amortir",
             "inventer", "épaissir", "étirer", "coopérer", "récupérer", "annuler", "faiblir", "ensorceler",
             "décaler",
             "ramollir", "gêner", "afférer", "combler", "enrayer", "commander", "choir", "acquiescer", "ôter",
             "bannir",
             "abréger", "égoutter", "louper", "reconstruire", "rendormir", "biper", "cuire", "resplendir",
             "errer",
             "pâter",
             "respecter", "tracer", "considérer", "déplaire", "étayer", "ailler", "morfondre", "honorer",
             "amarrer",
             "engager", "résoudre", "conter", "enfermer", "satisfaire", "informer", "soigner", "tordre",
             "tuer",
             "sortir",
             "homogénéiser", "consoler", "sangloter", "reparaître", "admirer", "organiser", "compiler",
             "implanter",
             "cerner", "scier", "rependre", "faillir", "opérer", "pécher", "est", "est"]
    other = ["d'", "s'", "m'", "l'", "j'", "n'", "t'", "y'"]

    word_list = stopwords + extras + verbs + other
    parsed_string = data.split()

    for word in parsed_string:
        if word in word_list:
            parsed_string.remove(word)

    return str(' '.join(parsed_string))